name: check_success

on:
  workflow_run:
    workflows: [deploy]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: 'failure'
          author_name: Check_success
          fields: repo,commit,message,author # action,eventName,ref,workflow,job,took 추가할 수 있음
          custom_payload: |
            {
            attachments: [{
              text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} 
              (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} 
              ${{ job.status }} in ${process.env.AS_TOOK}`
            }]
            }
          mention: here
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() 
